import { parseAbi } from 'viem'

export const METOK_ABI = parseAbi([
  'error ZeroAmount()',
  'error InvalidCardCount()',
  'error InvalidCardChoice()',
  'error InvalidEntropyAddress()',
  'error InvalidEntropyProvider()',
  'error InvalidEntropySequence()',
  'error InvalidBatchSize()',
  'error InvalidUserRandomNumber()',
  'error InvalidDeadline()',
  'error InsufficientValue()',
  'error UnauthorizedEntropy()',
  'error WrongPlayer()',
  'error WrongOrderKind()',
  'error NoPendingCurveOrder()',
  'error OrderNotReady()',
  'error NothingToClaim()',
  'error NotClaimOwner()',
  'error Insolvent()',
  'error DustAmount()',
  'error DirectMonTransferDisabled()',
  'error DirectTokenTransferToContractDisabled()',
  'error InvalidP2PPrice()',
  'error P2PSellOrderNotFound()',
  'error P2PBuyOrderNotFound()',
  'error NotP2PSeller()',
  'error NotP2PBuyer()',
  'error SlippageExceeded()',
  'error NativeTransferFailed()',
  'error AccountingInvariantBroken()',
  'error UnsupportedPriceLookback()',
  'error PriceChangeOverflow()',
  'function owner() view returns (address)',
  'function totalSupply() view returns (uint256)',
  'function balanceOf(address) view returns (uint256)',
  'function TOTAL_SUPPLY() view returns (uint256)',
  'function VIRTUAL_MON() view returns (uint256)',
  'function INITIAL_PRICE_WAD() view returns (uint256)',
  'function MIN_ORDER_LIFETIME() view returns (uint64)',
  'function MAX_ORDER_LIFETIME() view returns (uint64)',
  'function CARD_COUNT() view returns (uint32)',
  'function DEPLOYED_AT() view returns (uint64)',
  'function ENTROPY() view returns (address)',
  'function ENTROPY_PROVIDER() view returns (address)',
  'function realMonReserve() view returns (uint256)',
  'function curveTokenReserve() view returns (uint256)',
  'function pendingPlayMon() view returns (uint256)',
  'function claimReservedToken() view returns (uint256)',
  'function protocolSellEscrowToken() view returns (uint256)',
  'function p2pSellEscrowToken() view returns (uint256)',
  'function p2pBuyEscrowMon() view returns (uint256)',
  'function withdrawableMon(address) view returns (uint256)',
  'function circulatingSupply() view returns (uint256)',
  'function protocolPriceWad() view returns (uint256)',
  'function priceChangeFromInitialWad() view returns (int256)',
  'function priceChangeStats() view returns (int256[5] changesPctWad, bool[5] fullWindows, uint256[5] referencePricesWad, uint64[5] referenceTimestamps, int256 sinceLaunchPctWad)',
  'function quotePlay(uint256 monAmount) view returns (uint256)',
  'function quoteProtocolSell(uint256 tokenAmount) view returns (uint256)',
  'function entropyFee() view returns (uint256)',
  'function tokenBucketsBalanced() view returns (bool)',
  'function monAccountingSolvent() view returns (bool)',
  'function nextCurveOrderId() view returns (uint256)',
  'function nextCurveOrderToSettle() view returns (uint256)',
  'function canSettleNextCurveOrder() view returns (bool)',
  'function getCurveOrderState(uint256 orderId) view returns (uint8 kind,address user,uint256 amount,uint256 minOut,uint64 deadline,uint64 entropySequence,bool randomReady)',
  'function claims(uint256 orderId) view returns (address player,uint256 tokenAmount)',
  'function nextP2PSellOrderId() view returns (uint256)',
  'function nextP2PBuyOrderId() view returns (uint256)',
  'function p2pSellOrders(uint256) view returns (address seller,uint256 remainingToken,uint256 pricePerTokenWad)',
  'function p2pBuyOrders(uint256) view returns (address buyer,uint256 remainingMon,uint256 pricePerTokenWad)',
  'function quoteP2PSellOrderBuy(uint256 orderId,uint256 monAmount) view returns (uint256 tokenOut,uint256 monCost,uint256 refund)',
  'function quoteP2PBuyOrderFill(uint256 orderId,uint256 tokenAmount) view returns (uint256 tokenFilled,uint256 monOut)',
  'function submitPlay(uint256 betAmount,uint32 cardChoice,bytes32 userRandomNumber,uint256 minTokenOut,uint64 deadline) payable returns (uint256 orderId,uint64 sequenceNumber)',
  'function submitProtocolSell(uint256 tokenAmount,uint256 minMonOut,uint64 deadline) returns (uint256 orderId)',
  'function settleNextCurveOrder() returns (uint256 settledOrderId)',
  'function settleReadyCurveOrders(uint256 maxOrders) returns (uint256 settledCount)',
  'function claimReward(uint256 orderId)',
  'function createP2PSellOrder(uint256 tokenAmount,uint256 pricePerTokenWad) returns (uint256 orderId)',
  'function buyFromP2PSellOrder(uint256 orderId,uint256 minTokenOut) payable returns (uint256 tokenOut,uint256 monCost)',
  'function cancelP2PSellOrder(uint256 orderId)',
  'function createP2PBuyOrder(uint256 pricePerTokenWad) payable returns (uint256 orderId)',
  'function fillP2PBuyOrder(uint256 orderId,uint256 tokenAmount,uint256 minMonOut) returns (uint256 tokenFilled,uint256 monOut)',
  'function cancelP2PBuyOrder(uint256 orderId)',
  'function withdrawMon()',
  'event PlaySubmitted(uint256 indexed orderId,address indexed player,uint256 monAmount,uint32 cardChoice,uint256 minTokenOut,uint64 deadline,uint64 entropySequence,uint256 entropyFee)',
  'event EntropyRandomReady(uint256 indexed orderId,uint64 indexed sequence,uint256 randomWord)',
  'event EntropyCallbackIgnored(uint64 indexed sequence,uint256 indexed orderId,bytes32 reason)',
  'event PlaySettled(uint256 indexed orderId,address indexed player,bool eligible,bool refunded,bytes32 refundReason,uint32 winningCard,uint256 monAmount,uint256 tokenReward,uint256 realMonReserveAfter,uint256 curveTokenReserveAfter)',
  'event RewardClaimed(uint256 indexed orderId,address indexed player,uint256 tokenAmount)',
  'event ProtocolSellSubmitted(uint256 indexed orderId,address indexed seller,uint256 tokenAmount,uint256 minMonOut,uint64 deadline)',
  'event ProtocolSellSettled(uint256 indexed orderId,address indexed seller,uint256 tokenAmount,uint256 monCredit,uint256 realMonReserveAfter,uint256 curveTokenReserveAfter)',
  'event ProtocolSellCancelled(uint256 indexed orderId,address indexed seller,uint256 tokenReturned,bytes32 reason)',
  'event MonCreditCreated(address indexed account,uint256 amount,bytes32 indexed reason)',
  'event MonWithdrawn(address indexed account,uint256 amount)',
  'event P2PSellOrderCreated(uint256 indexed orderId,address indexed seller,uint256 tokenAmount,uint256 pricePerTokenWad)',
  'event P2PSellOrderFilled(uint256 indexed orderId,address indexed seller,address indexed buyer,uint256 tokenAmount,uint256 monAmount,uint256 remainingToken)',
  'event P2PSellOrderCancelled(uint256 indexed orderId,address indexed seller,uint256 tokenReturned)',
  'event P2PBuyOrderCreated(uint256 indexed orderId,address indexed buyer,uint256 monBudget,uint256 pricePerTokenWad)',
  'event P2PBuyOrderFilled(uint256 indexed orderId,address indexed buyer,address indexed seller,uint256 tokenAmount,uint256 monAmount,uint256 remainingMon)',
  'event P2PBuyOrderCancelled(uint256 indexed orderId,address indexed buyer,uint256 monRefund)',
  'event PriceCheckpoint(uint64 indexed timestamp,uint256 priceWad,uint8 indexed cadence)'
])
